/**
 * Catapult REST API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.12
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The Addresses model module.
* @module model/Addresses
* @version 1.0.12
*/
export default class Addresses {
    /**
    * Constructs a new <code>Addresses</code>.
    * @alias module:model/Addresses
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>Addresses</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Addresses} obj Optional instance to populate.
    * @return {module:model/Addresses} The populated <code>Addresses</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Addresses();

            
            
            

            if (data.hasOwnProperty('addresses')) {
                obj['addresses'] = ApiClient.convertToType(data['addresses'], ['String']);
            }
        }
        return obj;
    }

    /**
    * @member {Array.<String>} addresses
    */
    addresses = undefined;








}


