/*
 * Copyright 2019 NEM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 * Catapult REST API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.7.15
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import AccountDTO from './model/AccountDTO';
import AccountInfoDTO from './model/AccountInfoDTO';
import AccountMetaDTO from './model/AccountMetaDTO';
import AccountNamesDTO from './model/AccountNamesDTO';
import AccountPropertiesDTO from './model/AccountPropertiesDTO';
import AccountPropertiesInfoDTO from './model/AccountPropertiesInfoDTO';
import AccountPropertyDTO from './model/AccountPropertyDTO';
import AccountPropertyTypeEnum from './model/AccountPropertyTypeEnum';
import AccountsIds from './model/AccountsIds';
import AliasDTO from './model/AliasDTO';
import AliasTypeEnum from './model/AliasTypeEnum';
import AnnounceTransactionInfoDTO from './model/AnnounceTransactionInfoDTO';
import BlockDTO from './model/BlockDTO';
import BlockInfoDTO from './model/BlockInfoDTO';
import BlockMetaDTO from './model/BlockMetaDTO';
import BlockchainScoreDTO from './model/BlockchainScoreDTO';
import CommunicationTimestamps from './model/CommunicationTimestamps';
import HeightInfoDTO from './model/HeightInfoDTO';
import MerklePathItem from './model/MerklePathItem';
import MerkleProofInfoDTO from './model/MerkleProofInfoDTO';
import MerkleProofInfoPayload from './model/MerkleProofInfoPayload';
import MosaicDTO from './model/MosaicDTO';
import MosaicDefinitionDTO from './model/MosaicDefinitionDTO';
import MosaicIds from './model/MosaicIds';
import MosaicInfoDTO from './model/MosaicInfoDTO';
import MosaicMetaDTO from './model/MosaicMetaDTO';
import MosaicNamesDTO from './model/MosaicNamesDTO';
import MosaicPropertyDTO from './model/MosaicPropertyDTO';
import MosaicPropertyIdEnum from './model/MosaicPropertyIdEnum';
import MultisigAccountGraphInfoDTO from './model/MultisigAccountGraphInfoDTO';
import MultisigAccountInfoDTO from './model/MultisigAccountInfoDTO';
import MultisigDTO from './model/MultisigDTO';
import MultisigModificationTypeEnum from './model/MultisigModificationTypeEnum';
import NamespaceDTO from './model/NamespaceDTO';
import NamespaceIds from './model/NamespaceIds';
import NamespaceInfoDTO from './model/NamespaceInfoDTO';
import NamespaceMetaDTO from './model/NamespaceMetaDTO';
import NamespaceNameDTO from './model/NamespaceNameDTO';
import NamespaceTypeEnum from './model/NamespaceTypeEnum';
import NetworkTypeDTO from './model/NetworkTypeDTO';
import NetworkTypeEnum from './model/NetworkTypeEnum';
import NodeInfoDTO from './model/NodeInfoDTO';
import NodeTimeDTO from './model/NodeTimeDTO';
import ReceiptTypeEnum from './model/ReceiptTypeEnum';
import ResolutionEntryDTO from './model/ResolutionEntryDTO';
import ResolutionStatementDTO from './model/ResolutionStatementDTO';
import RolesTypeEnum from './model/RolesTypeEnum';
import ServerDTO from './model/ServerDTO';
import ServerInfoDTO from './model/ServerInfoDTO';
import SourceDTO from './model/SourceDTO';
import StatementsDTO from './model/StatementsDTO';
import StorageInfoDTO from './model/StorageInfoDTO';
import TransactionHashes from './model/TransactionHashes';
import TransactionIds from './model/TransactionIds';
import TransactionInfoDTO from './model/TransactionInfoDTO';
import TransactionMetaDTO from './model/TransactionMetaDTO';
import TransactionPayload from './model/TransactionPayload';
import TransactionStatementDTO from './model/TransactionStatementDTO';
import TransactionStatusDTO from './model/TransactionStatusDTO';
import UInt64DTO from './model/UInt64DTO';
import AccountRoutesApi from './api/AccountRoutesApi';
import BlockRoutesApi from './api/BlockRoutesApi';
import ChainRoutesApi from './api/ChainRoutesApi';
import DiagnosticRoutesApi from './api/DiagnosticRoutesApi';
import MosaicRoutesApi from './api/MosaicRoutesApi';
import NamespaceRoutesApi from './api/NamespaceRoutesApi';
import NetworkRoutesApi from './api/NetworkRoutesApi';
import NodeRoutesApi from './api/NodeRoutesApi';
import TransactionRoutesApi from './api/TransactionRoutesApi';


/**
* .<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var CatapultRestApiReference = require('index'); // See note below*.
* var xxxSvc = new CatapultRestApiReference.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new CatapultRestApiReference.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new CatapultRestApiReference.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new CatapultRestApiReference.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 0.7.15
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The AccountDTO model constructor.
     * @property {module:model/AccountDTO}
     */
    AccountDTO,

    /**
     * The AccountInfoDTO model constructor.
     * @property {module:model/AccountInfoDTO}
     */
    AccountInfoDTO,

    /**
     * The AccountMetaDTO model constructor.
     * @property {module:model/AccountMetaDTO}
     */
    AccountMetaDTO,

    /**
     * The AccountNamesDTO model constructor.
     * @property {module:model/AccountNamesDTO}
     */
    AccountNamesDTO,

    /**
     * The AccountPropertiesDTO model constructor.
     * @property {module:model/AccountPropertiesDTO}
     */
    AccountPropertiesDTO,

    /**
     * The AccountPropertiesInfoDTO model constructor.
     * @property {module:model/AccountPropertiesInfoDTO}
     */
    AccountPropertiesInfoDTO,

    /**
     * The AccountPropertyDTO model constructor.
     * @property {module:model/AccountPropertyDTO}
     */
    AccountPropertyDTO,

    /**
     * The AccountPropertyTypeEnum model constructor.
     * @property {module:model/AccountPropertyTypeEnum}
     */
    AccountPropertyTypeEnum,

    /**
     * The AccountsIds model constructor.
     * @property {module:model/AccountsIds}
     */
    AccountsIds,

    /**
     * The AliasDTO model constructor.
     * @property {module:model/AliasDTO}
     */
    AliasDTO,

    /**
     * The AliasTypeEnum model constructor.
     * @property {module:model/AliasTypeEnum}
     */
    AliasTypeEnum,

    /**
     * The AnnounceTransactionInfoDTO model constructor.
     * @property {module:model/AnnounceTransactionInfoDTO}
     */
    AnnounceTransactionInfoDTO,

    /**
     * The BlockDTO model constructor.
     * @property {module:model/BlockDTO}
     */
    BlockDTO,

    /**
     * The BlockInfoDTO model constructor.
     * @property {module:model/BlockInfoDTO}
     */
    BlockInfoDTO,

    /**
     * The BlockMetaDTO model constructor.
     * @property {module:model/BlockMetaDTO}
     */
    BlockMetaDTO,

    /**
     * The BlockchainScoreDTO model constructor.
     * @property {module:model/BlockchainScoreDTO}
     */
    BlockchainScoreDTO,

    /**
     * The CommunicationTimestamps model constructor.
     * @property {module:model/CommunicationTimestamps}
     */
    CommunicationTimestamps,

    /**
     * The HeightInfoDTO model constructor.
     * @property {module:model/HeightInfoDTO}
     */
    HeightInfoDTO,

    /**
     * The MerklePathItem model constructor.
     * @property {module:model/MerklePathItem}
     */
    MerklePathItem,

    /**
     * The MerkleProofInfoDTO model constructor.
     * @property {module:model/MerkleProofInfoDTO}
     */
    MerkleProofInfoDTO,

    /**
     * The MerkleProofInfoPayload model constructor.
     * @property {module:model/MerkleProofInfoPayload}
     */
    MerkleProofInfoPayload,

    /**
     * The MosaicDTO model constructor.
     * @property {module:model/MosaicDTO}
     */
    MosaicDTO,

    /**
     * The MosaicDefinitionDTO model constructor.
     * @property {module:model/MosaicDefinitionDTO}
     */
    MosaicDefinitionDTO,

    /**
     * The MosaicIds model constructor.
     * @property {module:model/MosaicIds}
     */
    MosaicIds,

    /**
     * The MosaicInfoDTO model constructor.
     * @property {module:model/MosaicInfoDTO}
     */
    MosaicInfoDTO,

    /**
     * The MosaicMetaDTO model constructor.
     * @property {module:model/MosaicMetaDTO}
     */
    MosaicMetaDTO,

    /**
     * The MosaicNamesDTO model constructor.
     * @property {module:model/MosaicNamesDTO}
     */
    MosaicNamesDTO,

    /**
     * The MosaicPropertyDTO model constructor.
     * @property {module:model/MosaicPropertyDTO}
     */
    MosaicPropertyDTO,

    /**
     * The MosaicPropertyIdEnum model constructor.
     * @property {module:model/MosaicPropertyIdEnum}
     */
    MosaicPropertyIdEnum,

    /**
     * The MultisigAccountGraphInfoDTO model constructor.
     * @property {module:model/MultisigAccountGraphInfoDTO}
     */
    MultisigAccountGraphInfoDTO,

    /**
     * The MultisigAccountInfoDTO model constructor.
     * @property {module:model/MultisigAccountInfoDTO}
     */
    MultisigAccountInfoDTO,

    /**
     * The MultisigDTO model constructor.
     * @property {module:model/MultisigDTO}
     */
    MultisigDTO,

    /**
     * The MultisigModificationTypeEnum model constructor.
     * @property {module:model/MultisigModificationTypeEnum}
     */
    MultisigModificationTypeEnum,

    /**
     * The NamespaceDTO model constructor.
     * @property {module:model/NamespaceDTO}
     */
    NamespaceDTO,

    /**
     * The NamespaceIds model constructor.
     * @property {module:model/NamespaceIds}
     */
    NamespaceIds,

    /**
     * The NamespaceInfoDTO model constructor.
     * @property {module:model/NamespaceInfoDTO}
     */
    NamespaceInfoDTO,

    /**
     * The NamespaceMetaDTO model constructor.
     * @property {module:model/NamespaceMetaDTO}
     */
    NamespaceMetaDTO,

    /**
     * The NamespaceNameDTO model constructor.
     * @property {module:model/NamespaceNameDTO}
     */
    NamespaceNameDTO,

    /**
     * The NamespaceTypeEnum model constructor.
     * @property {module:model/NamespaceTypeEnum}
     */
    NamespaceTypeEnum,

    /**
     * The NetworkTypeDTO model constructor.
     * @property {module:model/NetworkTypeDTO}
     */
    NetworkTypeDTO,

    /**
     * The NetworkTypeEnum model constructor.
     * @property {module:model/NetworkTypeEnum}
     */
    NetworkTypeEnum,

    /**
     * The NodeInfoDTO model constructor.
     * @property {module:model/NodeInfoDTO}
     */
    NodeInfoDTO,

    /**
     * The NodeTimeDTO model constructor.
     * @property {module:model/NodeTimeDTO}
     */
    NodeTimeDTO,

    /**
     * The ReceiptTypeEnum model constructor.
     * @property {module:model/ReceiptTypeEnum}
     */
    ReceiptTypeEnum,

    /**
     * The ResolutionEntryDTO model constructor.
     * @property {module:model/ResolutionEntryDTO}
     */
    ResolutionEntryDTO,

    /**
     * The ResolutionStatementDTO model constructor.
     * @property {module:model/ResolutionStatementDTO}
     */
    ResolutionStatementDTO,

    /**
     * The RolesTypeEnum model constructor.
     * @property {module:model/RolesTypeEnum}
     */
    RolesTypeEnum,

    /**
     * The ServerDTO model constructor.
     * @property {module:model/ServerDTO}
     */
    ServerDTO,

    /**
     * The ServerInfoDTO model constructor.
     * @property {module:model/ServerInfoDTO}
     */
    ServerInfoDTO,

    /**
     * The SourceDTO model constructor.
     * @property {module:model/SourceDTO}
     */
    SourceDTO,

    /**
     * The StatementsDTO model constructor.
     * @property {module:model/StatementsDTO}
     */
    StatementsDTO,

    /**
     * The StorageInfoDTO model constructor.
     * @property {module:model/StorageInfoDTO}
     */
    StorageInfoDTO,

    /**
     * The TransactionHashes model constructor.
     * @property {module:model/TransactionHashes}
     */
    TransactionHashes,

    /**
     * The TransactionIds model constructor.
     * @property {module:model/TransactionIds}
     */
    TransactionIds,

    /**
     * The TransactionInfoDTO model constructor.
     * @property {module:model/TransactionInfoDTO}
     */
    TransactionInfoDTO,

    /**
     * The TransactionMetaDTO model constructor.
     * @property {module:model/TransactionMetaDTO}
     */
    TransactionMetaDTO,

    /**
     * The TransactionPayload model constructor.
     * @property {module:model/TransactionPayload}
     */
    TransactionPayload,

    /**
     * The TransactionStatementDTO model constructor.
     * @property {module:model/TransactionStatementDTO}
     */
    TransactionStatementDTO,

    /**
     * The TransactionStatusDTO model constructor.
     * @property {module:model/TransactionStatusDTO}
     */
    TransactionStatusDTO,

    /**
     * The UInt64DTO model constructor.
     * @property {module:model/UInt64DTO}
     */
    UInt64DTO,

    /**
    * The AccountRoutesApi service constructor.
    * @property {module:api/AccountRoutesApi}
    */
    AccountRoutesApi,

    /**
    * The BlockRoutesApi service constructor.
    * @property {module:api/BlockRoutesApi}
    */
    BlockRoutesApi,

    /**
    * The ChainRoutesApi service constructor.
    * @property {module:api/ChainRoutesApi}
    */
    ChainRoutesApi,

    /**
    * The DiagnosticRoutesApi service constructor.
    * @property {module:api/DiagnosticRoutesApi}
    */
    DiagnosticRoutesApi,

    /**
    * The MosaicRoutesApi service constructor.
    * @property {module:api/MosaicRoutesApi}
    */
    MosaicRoutesApi,

    /**
    * The NamespaceRoutesApi service constructor.
    * @property {module:api/NamespaceRoutesApi}
    */
    NamespaceRoutesApi,

    /**
    * The NetworkRoutesApi service constructor.
    * @property {module:api/NetworkRoutesApi}
    */
    NetworkRoutesApi,

    /**
    * The NodeRoutesApi service constructor.
    * @property {module:api/NodeRoutesApi}
    */
    NodeRoutesApi,

    /**
    * The TransactionRoutesApi service constructor.
    * @property {module:api/TransactionRoutesApi}
    */
    TransactionRoutesApi
};
