/*
 * Copyright 2019 NEM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/*
 * Catapult REST API Reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.7.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.MosaicDTO;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for AccountDTO
 */
public class AccountDTOTest {
    private final AccountDTO model = new AccountDTO();

    /**
     * Model tests for AccountDTO
     */
    @Test
    public void testAccountDTO() {
        // TODO: test AccountDTO
    }

    /**
     * Test the property 'address'
     */
    @Test
    public void addressTest() {
        // TODO: test address
    }

    /**
     * Test the property 'addressHeight'
     */
    @Test
    public void addressHeightTest() {
        // TODO: test addressHeight
    }

    /**
     * Test the property 'publicKey'
     */
    @Test
    public void publicKeyTest() {
        // TODO: test publicKey
    }

    /**
     * Test the property 'publicKeyHeight'
     */
    @Test
    public void publicKeyHeightTest() {
        // TODO: test publicKeyHeight
    }

    /**
     * Test the property 'mosaics'
     */
    @Test
    public void mosaicsTest() {
        // TODO: test mosaics
    }

    /**
     * Test the property 'importance'
     */
    @Test
    public void importanceTest() {
        // TODO: test importance
    }

    /**
     * Test the property 'importanceHeight'
     */
    @Test
    public void importanceHeightTest() {
        // TODO: test importanceHeight
    }

}
