/*
 * Copyright 2019 NEM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/*
 * Catapult REST API Reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.7.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for BlockMetaDTO
 */
public class BlockMetaDTOTest {
    private final BlockMetaDTO model = new BlockMetaDTO();

    /**
     * Model tests for BlockMetaDTO
     */
    @Test
    public void testBlockMetaDTO() {
        // TODO: test BlockMetaDTO
    }

    /**
     * Test the property 'hash'
     */
    @Test
    public void hashTest() {
        // TODO: test hash
    }

    /**
     * Test the property 'generationHash'
     */
    @Test
    public void generationHashTest() {
        // TODO: test generationHash
    }

    /**
     * Test the property 'subCacheMerkleRoots'
     */
    @Test
    public void subCacheMerkleRootsTest() {
        // TODO: test subCacheMerkleRoots
    }

    /**
     * Test the property 'totalFee'
     */
    @Test
    public void totalFeeTest() {
        // TODO: test totalFee
    }

    /**
     * Test the property 'numTransactions'
     */
    @Test
    public void numTransactionsTest() {
        // TODO: test numTransactions
    }

    /**
     * Test the property 'numStatements'
     */
    @Test
    public void numStatementsTest() {
        // TODO: test numStatements
    }

}
