/*
 * Copyright 2019 NEM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/*
 * Catapult REST API Reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.7.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for BlockDTO
 */
public class BlockDTOTest {
    private final BlockDTO model = new BlockDTO();

    /**
     * Model tests for BlockDTO
     */
    @Test
    public void testBlockDTO() {
        // TODO: test BlockDTO
    }

    /**
     * Test the property 'signature'
     */
    @Test
    public void signatureTest() {
        // TODO: test signature
    }

    /**
     * Test the property 'signer'
     */
    @Test
    public void signerTest() {
        // TODO: test signer
    }

    /**
     * Test the property 'version'
     */
    @Test
    public void versionTest() {
        // TODO: test version
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'height'
     */
    @Test
    public void heightTest() {
        // TODO: test height
    }

    /**
     * Test the property 'timestamp'
     */
    @Test
    public void timestampTest() {
        // TODO: test timestamp
    }

    /**
     * Test the property 'difficulty'
     */
    @Test
    public void difficultyTest() {
        // TODO: test difficulty
    }

    /**
     * Test the property 'feeMultiplier'
     */
    @Test
    public void feeMultiplierTest() {
        // TODO: test feeMultiplier
    }

    /**
     * Test the property 'previousBlockHash'
     */
    @Test
    public void previousBlockHashTest() {
        // TODO: test previousBlockHash
    }

    /**
     * Test the property 'blockTransactionsHash'
     */
    @Test
    public void blockTransactionsHashTest() {
        // TODO: test blockTransactionsHash
    }

    /**
     * Test the property 'blockReceiptsHash'
     */
    @Test
    public void blockReceiptsHashTest() {
        // TODO: test blockReceiptsHash
    }

    /**
     * Test the property 'stateHash'
     */
    @Test
    public void stateHashTest() {
        // TODO: test stateHash
    }

    /**
     * Test the property 'beneficiary'
     */
    @Test
    public void beneficiaryTest() {
        // TODO: test beneficiary
    }

}
