/*
 * Copyright 2019 NEM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/*
 * Catapult REST API Reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.7.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.AliasDTO;
import org.openapitools.client.model.NamespaceTypeEnum;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for NamespaceDTO
 */
public class NamespaceDTOTest {
    private final NamespaceDTO model = new NamespaceDTO();

    /**
     * Model tests for NamespaceDTO
     */
    @Test
    public void testNamespaceDTO() {
        // TODO: test NamespaceDTO
    }

    /**
     * Test the property 'owner'
     */
    @Test
    public void ownerTest() {
        // TODO: test owner
    }

    /**
     * Test the property 'ownerAddress'
     */
    @Test
    public void ownerAddressTest() {
        // TODO: test ownerAddress
    }

    /**
     * Test the property 'startHeight'
     */
    @Test
    public void startHeightTest() {
        // TODO: test startHeight
    }

    /**
     * Test the property 'endHeight'
     */
    @Test
    public void endHeightTest() {
        // TODO: test endHeight
    }

    /**
     * Test the property 'depth'
     */
    @Test
    public void depthTest() {
        // TODO: test depth
    }

    /**
     * Test the property 'level0'
     */
    @Test
    public void level0Test() {
        // TODO: test level0
    }

    /**
     * Test the property 'level1'
     */
    @Test
    public void level1Test() {
        // TODO: test level1
    }

    /**
     * Test the property 'level2'
     */
    @Test
    public void level2Test() {
        // TODO: test level2
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'alias'
     */
    @Test
    public void aliasTest() {
        // TODO: test alias
    }

    /**
     * Test the property 'parentId'
     */
    @Test
    public void parentIdTest() {
        // TODO: test parentId
    }

}
