/*
 * Copyright 2019 NEM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/*
 * Catapult REST API Reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.7.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.ResolutionStatementDTO;
import org.openapitools.client.model.TransactionStatementDTO;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for StatementsDTO
 */
public class StatementsDTOTest {
    private final StatementsDTO model = new StatementsDTO();

    /**
     * Model tests for StatementsDTO
     */
    @Test
    public void testStatementsDTO() {
        // TODO: test StatementsDTO
    }

    /**
     * Test the property 'transactionStatements'
     */
    @Test
    public void transactionStatementsTest() {
        // TODO: test transactionStatements
    }

    /**
     * Test the property 'addressResolutionStatements'
     */
    @Test
    public void addressResolutionStatementsTest() {
        // TODO: test addressResolutionStatements
    }

    /**
     * Test the property 'mosaicResolutionStatements'
     */
    @Test
    public void mosaicResolutionStatementsTest() {
        // TODO: test mosaicResolutionStatements
    }

}
