/*
 * Copyright 2019 NEM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/*
 * Catapult REST API Reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.7.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.ServerDTO;
import org.openapitools.client.model.StorageInfoDTO;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DiagnosticRoutesApi
 */
@Ignore
public class DiagnosticRoutesApiTest {

    private final DiagnosticRoutesApi api = new DiagnosticRoutesApi();

    
    /**
     * Get the storage information of the node
     *
     * Returns diagnostic information about the node storage.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getDiagnosticStorageTest() throws ApiException {
        StorageInfoDTO response = api.getDiagnosticStorage();

        // TODO: test validations
    }
    
    /**
     * Get the version of the running rest component
     *
     * Returns the version of the running rest component.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getServerInfoTest() throws ApiException {
        ServerDTO response = api.getServerInfo();

        // TODO: test validations
    }
    
}
