/*
 * Copyright 2019 NEM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/*
 * Catapult REST API Reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.7.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.MosaicIds;
import org.openapitools.client.model.MosaicInfoDTO;
import org.openapitools.client.model.MosaicNamesDTO;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for MosaicRoutesApi
 */
@Ignore
public class MosaicRoutesApiTest {

    private final MosaicRoutesApi api = new MosaicRoutesApi();

    
    /**
     * Get mosaic information
     *
     * Gets the mosaic definition for a given mosaicId.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getMosaicTest() throws ApiException {
        String mosaicId = null;
        MosaicInfoDTO response = api.getMosaic(mosaicId);

        // TODO: test validations
    }
    
    /**
     * Get mosaics information for an array of mosaics
     *
     * Gets an array of mosaic definition.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getMosaicsTest() throws ApiException {
        MosaicIds mosaicIds = null;
        List<MosaicInfoDTO> response = api.getMosaics(mosaicIds);

        // TODO: test validations
    }
    
    /**
     * Get readable names for a set of mosaics
     *
     * Returns friendly names for mosaics.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getMosaicsNamesTest() throws ApiException {
        MosaicIds mosaicIds = null;
        List<MosaicNamesDTO> response = api.getMosaicsNames(mosaicIds);

        // TODO: test validations
    }
    
}
