/*
 * Copyright 2019 NEM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/*
 * Catapult REST API Reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.7.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.AccountIds;
import org.openapitools.client.model.NamespaceIds;
import org.openapitools.client.model.NamespaceInfoDTO;
import org.openapitools.client.model.NamespaceNameDTO;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for NamespaceRoutesApi
 */
@Ignore
public class NamespaceRoutesApiTest {

    private final NamespaceRoutesApi api = new NamespaceRoutesApi();

    
    /**
     * Get namespace information
     *
     * Gets the namespace for a given namespaceId.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getNamespaceTest() throws ApiException {
        String namespaceId = null;
        NamespaceInfoDTO response = api.getNamespace(namespaceId);

        // TODO: test validations
    }
    
    /**
     * Get namespaces owned by an account
     *
     * Gets an array of namespaces for a given account address.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getNamespacesFromAccountTest() throws ApiException {
        String accountId = null;
        Integer pageSize = null;
        String id = null;
        List<NamespaceInfoDTO> response = api.getNamespacesFromAccount(accountId, pageSize, id);

        // TODO: test validations
    }
    
    /**
     * Get namespaces for given array of addresses
     *
     * Gets namespaces for a given array of addresses.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getNamespacesFromAccountsTest() throws ApiException {
        AccountIds accountIds = null;
        Integer pageSize = null;
        String id = null;
        List<NamespaceInfoDTO> response = api.getNamespacesFromAccounts(accountIds, pageSize, id);

        // TODO: test validations
    }
    
    /**
     * Get readable names for a set of namespaces
     *
     * Returns friendly names for namespaces.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getNamespacesNamesTest() throws ApiException {
        NamespaceIds namespaceIds = null;
        List<NamespaceNameDTO> response = api.getNamespacesNames(namespaceIds);

        // TODO: test validations
    }
    
}
