/*
 * Copyright 2019 NEM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/*
 * Catapult REST API Reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.7.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.NodeInfoDTO;
import org.openapitools.client.model.NodeTimeDTO;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for NodeRoutesApi
 */
@Ignore
public class NodeRoutesApiTest {

    private final NodeRoutesApi api = new NodeRoutesApi();

    
    /**
     * Get the node information
     *
     * Supplies additional information about the application running on a node. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getNodeInfoTest() throws ApiException {
        NodeInfoDTO response = api.getNodeInfo();

        // TODO: test validations
    }
    
    /**
     * Get the node time
     *
     * Gets the node time at the moment the reply was sent and received.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getNodeTimeTest() throws ApiException {
        NodeTimeDTO response = api.getNodeTime();

        // TODO: test validations
    }
    
}
