// tslint:disable
/*
 * Copyright 2019 NEM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 * Catapult REST API Reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.7.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface BlockDTO
 */
export interface BlockDTO {
    /**
     * The signature of the block. The signature was generated by the signer and can be used to validate tha the entity data was not modified by a node. 
     * @type {string}
     * @memberof BlockDTO
     */
    signature: string;
    /**
     * The public key of the block harvester formatted as hexadecimal.
     * @type {string}
     * @memberof BlockDTO
     */
    signer: string;
    /**
     * The entity version. The higher byte represents the network identifier: * 0x68 (MAIN_NET) - Public main network. * 0x98 (TEST_NET) - Public test network. * 0x60 (MIJIN) - Private network. * 0x90 (MIJIN_TEST) - Private test network. 
     * @type {number}
     * @memberof BlockDTO
     */
    version: number;
    /**
     * The block type: * 0x8043 (32835 decimal) - Nemesis block. * 0x8143 (33091 decimal) - Regular block. 
     * @type {number}
     * @memberof BlockDTO
     */
    type: number;
    /**
     * 
     * @type {Array<number>}
     * @memberof BlockDTO
     */
    height: Array<number>;
    /**
     * 
     * @type {Array<number>}
     * @memberof BlockDTO
     */
    timestamp: Array<number>;
    /**
     * 
     * @type {Array<number>}
     * @memberof BlockDTO
     */
    difficulty: Array<number>;
    /**
     * The fee multiplier applied to transactions contained in block.
     * @type {number}
     * @memberof BlockDTO
     */
    feeMultiplier: number;
    /**
     * The hash of the previous block.
     * @type {string}
     * @memberof BlockDTO
     */
    previousBlockHash: string;
    /**
     * The transactions included in a block are hashed forming a merkle tree. The root of the tree summarizes them. 
     * @type {string}
     * @memberof BlockDTO
     */
    blockTransactionsHash: string;
    /**
     * The collection of receipts  are hashed into a merkle tree and linked to a block. The block header stores the root hash. 
     * @type {string}
     * @memberof BlockDTO
     */
    blockReceiptsHash: string;
    /**
     * For each block, the state of the blockchain is stored in RocksDB, forming a patricia tree. The root of the tree summarizes the state of the blockchain for the given block. 
     * @type {string}
     * @memberof BlockDTO
     */
    stateHash: string;
    /**
     * The public key of the optional beneficiary designated by harvester.
     * @type {string}
     * @memberof BlockDTO
     */
    beneficiary: string;
}
