// tslint:disable
/*
 * Copyright 2019 NEM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 * Catapult REST API Reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.7.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    AliasDTO,
    NamespaceTypeEnum,
} from './';

/**
 * @export
 * @interface NamespaceDTO
 */
export interface NamespaceDTO {
    /**
     * The public key of the owner of the namespace.
     * @type {string}
     * @memberof NamespaceDTO
     */
    owner: string;
    /**
     * The address of the owner of the namespace in hexadecimal.
     * @type {string}
     * @memberof NamespaceDTO
     */
    ownerAddress: string;
    /**
     * 
     * @type {Array<number>}
     * @memberof NamespaceDTO
     */
    startHeight: Array<number>;
    /**
     * 
     * @type {Array<number>}
     * @memberof NamespaceDTO
     */
    endHeight: Array<number>;
    /**
     * The level of the namespace.
     * @type {number}
     * @memberof NamespaceDTO
     */
    depth: number;
    /**
     * 
     * @type {Array<number>}
     * @memberof NamespaceDTO
     */
    level0: Array<number>;
    /**
     * 
     * @type {Array<number>}
     * @memberof NamespaceDTO
     */
    level1?: Array<number>;
    /**
     * 
     * @type {Array<number>}
     * @memberof NamespaceDTO
     */
    level2?: Array<number>;
    /**
     * 
     * @type {NamespaceTypeEnum}
     * @memberof NamespaceDTO
     */
    type: NamespaceTypeEnum;
    /**
     * 
     * @type {AliasDTO}
     * @memberof NamespaceDTO
     */
    alias: AliasDTO;
    /**
     * 
     * @type {Array<number>}
     * @memberof NamespaceDTO
     */
    parentId: Array<number>;
}
